<Project>

	<PropertyGroup>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
		<CentralPackageTransitivePinningEnabled>false</CentralPackageTransitivePinningEnabled>
	</PropertyGroup>

	<ItemGroup>
		<PackageVersion Include="WSCT.Core" Version="6.7.1" />
	</ItemGroup>

</Project>